### ISSUE TITLE
Documentation url paths

### ISSUE THREAD

**Issue by Nigui** [unik-name/docs.uns.network#7]
Could be great to update current documentation URL paths, because they're not very friendly : 

For exemples : 

- `https://docs.uns.network/uns-usethenetwork` --> `https://docs.uns.network/use`
- `https://docs.uns.network/uns-introduction` --> `https://docs.uns.network/introduction`

We could simply, remove `uns` prefix in all top routes.

**Comment by dlecan** [comment]
Cc @laurentlourenco

**Comment by laurentlourenco** [comment]
done with branch and pull request https://github.com/unik-name/docs.uns.network/pull/65
